name: Deploy Application

on:
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  # Job 1: Checkout Code
  JOB1:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.3.2'  # Ensure Terraform version matches your setup

      # Step 3: Configure AWS credentials for Terraform
      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init
        working-directory: terraform  # Ensure Terraform runs from the correct directory

      # Step 5: Terraform Plan
      - name: Terraform Plan
        run: terraform plan 
        working-directory: terraform

      # Step 6: Apply Terraform to create resources 
      - name: Terraform Apply
        run: terraform apply -auto-approve 
        working-directory: terraform  # Ensure Terraform runs from the correct directory
